athens_fires_2024: 

  file_templates : [ 'GRIBPFDEODathens_fires_2024+%LLLLh00m00s','ICMSHDEOD+%LLLLh00m00s.sfx' ]

  atos:
     path_template : 'ectmp:/nhad/deode/CY48t3_AROME_athens_fires_2024/archive/%Y/%m/%d/%H/'

  lumi_transfer:
     path_template : ''
  
  domain : 
     name : 'athens_fires_2024'
     resolution : 500
     levels : 90
