corsica_flooding_2024: 

  file_templates : [ 'GRIBPFDEODCUBIC_1500x1500_500m+%LLLLh00m00s','ICMSHDEOD+%LLLLh00m00s.sfx' ]

  atos:
     path_template : 'ectmp:/nhad/deode/CY48t3_AROME_corsica_flooding/archive/%Y/%m/%d/%H/'

  lumi_transfer:
     path_template : ''
  
  domain : 
     name : 'CUBIC_1500x1500_500m'
     resolution : 500
     levels : 90
