cy43_deode_ref_fin: 

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/fie/harmonie/cy43_deode_ref_fin/%Y/%m/%d/%H/'

  domain : 
     name : 'METCOOP25D'
     resolution : 2500
     levels : 65


cy46h1_EDT_ref_fin:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/fie/harmonie/cy46h1_EDT_ref_fin/%Y/%m/%d/%H/'

  domain :
     name : 'METCOOP25D'
     resolution : 2500
     levels : 65


cy46h1_EDT_s5d_n750:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/fie/harmonie/cy46h1_EDT_s5d_n750/%Y/%m/%d/%H/'

  domain :
     name : 'HERCULES750'
     resolution : 750
     levels : 90


cy46h1_EDT_s0d_n750_1500gp:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/fie/harmonie/cy46h1_EDT_s0d_n750_1500gp/%Y/%m/%d/%H/'

  domain :
     name : 'HERCULES750_1500'
     resolution : 750
     levels : 90


cy46h1_EDT_s0d_n500_1500gp:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/fie/harmonie/cy46h1_EDT_s0d_n500_1500gp/%Y/%m/%d/%H/'

  domain :
     name : 'HERCULES500_1500'
     resolution : 500
     levels : 90


cy46h1_EDT_s0d_n200_1500gp_pgdMPI:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/fie/harmonie/cy46h1_EDT_s0d_n200_1500gp_pgdMPI/%Y/%m/%d/%H/'

  domain :
     name : 'HERCULES200_1500'
     resolution : 200
     levels : 90


cy46h1_DEDT_500m_1500gp_Conn3:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/fie/harmonie/cy46h1_DEDT_500m_1500gp_Conn3/%Y/%m/%d/%H/'

  lumi_transfer:
     path_template : '/scratch/project_465000527/de_33050_common_data/cases/finland_2017/cy46h1_DEDT_500m_1500gp_Conn3/%Y/%m/%d/%H/'

  domain :
     name : 'Con3_500_1500'
     resolution : 500
     levels : 90

Prot_F17_750_1500:

  file_templates : ['sfx_%Y-%m-%dT%H0000+0%LLLh00m00s.grib','GRIBPFDEODProt_F17_750_1500+0%LLLh00m00s']
  atos:
     path_template : 'ectmp:/fie/deode/Prot_F17_750_1500/archive/%Y/%m/%d/%H/'

  lumi_transfer:
     path_template : '/scratch/project_465000527/de_33050_common_data/cases/finland_2017/Prot_F17_750_1500/%Y/%m/%d/%H/'

  domain :
     name : 'Prot_F17_750_1500'
     resolution : 750
     levels : 90


Prot_F17_500_1500:

  file_templates : ['sfx_%Y-%m-%dT%H0000+0%LLLh00m00s.grib','GRIBPFDEODProt_F17_500_1500+0%LLLh00m00s']

  atos:
     path_template : 'ectmp:/fie/deode/Prot_F17_500_1500/archive/%Y/%m/%d/%H/'

  lumi_transfer:
     path_template : '/scratch/project_465000527/de_33050_common_data/cases/finland_2017/Prot_F17_500_1500/%Y/%m/%d/%H/'

  domain :
     name : 'Prot_F17_500_1500'
     resolution : 500
     levels : 90


Prot_v040_FI7_750_1500:

  file_templates : ['GRIBDEOD+0%LLLh00m00s.sfx','GRIBPFDEODcaseFin2017+0%LLLh00m00s']

  atos:
     path_template : 'ectmp:/fie/deode/caseFin2017/archive/%Y/%m/%d/%H/'

  lumi_transfer:
     path_template : '/scratch/project_465000527/de_33050_common_data/cases/finland_2017/Prot_v040_FI7_750_1500/%Y/%m/%d/%H/'

  domain :
     name : 'caseFin2017'
     resolution : 750
     levels : 90