Sweden_heatwave_20240903: 

  file_templates : ['GRIBPFDEODSweden500+%LLLLh00m00s','ICMSHDEOD+%LLLLh00m00s.sfx']

  atos:
          path_template : 'ectmp:/sbyk/deode/CY48t3_AROME_Sweden500/archive/%Y/%m/%d/%H/'

  domain : 
    name : 'Sweden500'
    resolution : 500
    levels : 90
