Finland_convection_20240906: 

  file_templates : ['GRIBPFDEODFinland500+%LLLLh00m00s','ICMSHDEOD+%LLLLh00m00s.sfx']

  atos:
          path_template : 'ectmp:/sbyk/deode/CY48t3_AROME_Finland500/archive/%Y/%m/%d/%H/'

  domain : 
    name : 'Finland500'
    resolution : 500
    levels : 90
