name: Test local install

on:
  workflow_dispatch:
  push:
      branches: [main, develop]
  pull_request:

jobs:
  local_install:

    runs-on: ubuntu-latest
    strategy:
        max-parallel: 5
        matrix:
          python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: false
        channels: conda-forge
        miniforge-version: latest
        activate-environment: test
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        pip install --upgrade pip
        pip install .

    - name: Conda list
      run: conda list
    
    - name: Test local install
      run: dcmdb chase -list
